language: python
python:
  - 2.7
#env:
#  matrix:
#    - TEST_TYPE=default
#    - TEST_TYPE=quick
#    - TEST_TYPE=slow
install:
  - export chroot="$PWD"/buildroot.i386
  - .travis/setup_chroot.sh
script:
  - .travis/test.sh
  - .travis/build.sh
