language: python
sudo: false
python:
  - 2.7
branches:
  except:
    - windows-build
env:
  global:
    - OSXREPO=timfel/RSqueak-MacOSXBuild
    - TEST_TYPE=default 
  matrix:
    - BUILD_ARCH=32bit BUILD_TYPE=test
    - BUILD_ARCH=32bit BUILD_TYPE=build
    #- BUILD_ARCH=armv6 BUILD_TYPE=build SB2="$PWD/raspbian_arm" SB2NAME="rasp"
    #- BUILD_ARCH=armv7 BUILD_TYPE=build
install:
  - .travis/trigger-osx-build.sh || echo 0
  - .travis/install_requirements.sh
script:
  - if [ "$BUILD_TYPE" == test ]; then .travis/test.sh; fi
  - if [ "$BUILD_TYPE" == build ]; then .travis/build-linux.sh; fi
addons:
  apt:
    packages:
      - build-essential
      - libffi-dev
      - python-dev
      - libffi6:i386
      - libbz2-1.0:i386
      - libexpat1:i386
      - zlib1g:i386
      - libssl1.0.0:i386
      - libgcrypt11:i386
      - libtinfo5:i386
      - gcc-multilib
      - libfreetype6:i386
      - libsdl1.2-dev:i386
      - libasound2-dev:i386
      - libxt-dev:i386
      - libxext-dev:i386
      - libglu1-mesa-dev:i386
      - libglu1-mesa:i386
      - libgl1-mesa-dev:i386
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - libglapi-mesa:i386
      - debootstrap
      - qemu-user-static
      - binfmt-support
      - sbuild
      - scratchbox2
      - gcc-arm-linux-gnueabihf
      - libstdc++6:i386
      - schroot
      - qemu-system
cache:
  directories:
  - .build/pypy
  - .build/rsdl
  - .build/squeak
